version: 2.1

workflows:
  version: 2
  build-test-and-deploy:
   jobs:
    - test 
    - build:
        requires:
         - test
      

jobs:
 test:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: install dependencies 
        command: npm install
   
 build:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: save-dev @types/react-router-dom    
        command: npm i --save-dev @types/react-router-dom 

    - run:
        name: build
        command: npm run build
