version: 2.1

workflows:
  version: 2
  react-and-deploy:
   jobs:
    - react 
    

jobs:
 react:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: install dependencies 
        command: npm install --save @types/react-router-dom
   
