version: 2.1

workflows:
  version: 2
  build-react-and-deploy:
   jobs:
    - react 
    - build:
        requires:
         - react
      

jobs:
 react:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: install dependencies 
        command: npm i --save-dev @types/react-router-dom
   
 build:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: install dependencies
        command: npm install
    - run:
        name: build
        command: npm run build
