version: 2.1

workflows:
  version: 2
  build-and-deploy:
   jobs:
    - React
    - build
      
      

jobs:
 React:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: install dependencies 
        command: npm install --save react-router-dom
    

 build:
  docker:
    - image: cimg/node:14.17.3
  steps:
    - checkout
    - run:
        name: install dependencies
        command: npm install --save react-router-dom
    - run:
        name: build
        command: npm run build
